name: hackathon_blood_donation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  awesome_dialog: ^3.1.0
  firebase_core: ^2.22.0
  easy_localization: ^3.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.6

flutter: 
  uses-material-design: true
  assets:
    - assets/l10n/

